/**
 * @param {import('@docusaurus/plugin-content-docs').SidebarsConfig} param0
 */
const sidebars = {
  tutorialSidebar: [{
    type: 'autogenerated',
    dirName: '.',
  }],
};

module.exports = sidebars;
