import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Manual sidebar with chapter numbers
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: Robotic Nervous System',
      items: [{type: 'autogenerated', dirName: '01-robotic-nervous-system'}],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin Simulation',
      items: [{type: 'autogenerated', dirName: '02-digital-twin-simulation'}],
    },
    {
      type: 'category',
      label: 'Module 3: AI Robot Brain Isaac',
      items: [{type: 'autogenerated', dirName: '03-ai-robot-brain-isaac'}],
    },
    {
      type: 'category',
      label: 'Module 4: Vision Language Action',
      items: [{type: 'autogenerated', dirName: '04-vision-language-action'}],
    },
    // Keep the tutorial sections as they are
    {
      type: 'category',
      label: 'Tutorials',
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    },
    {
      type: 'category',
      label: 'Tutorial Extras',
      items: [{type: 'autogenerated', dirName: 'tutorial-extras'}],
    },
  ],
};

export default sidebars;
